### ISSUE TITLE
non-zero exit status, any suggestions on how to fix this problem?

### ISSUE THREAD

**Issue by saramasarone** [dswatson/bioplotr#1]
Hi David, 

I was trying to install bioplotr to try some of the nice plots you showed in the markdown related to the package. However, when I install it (using the lines of code you provided) I get these errors (see below). I tried to install it more than once and and I also restarted R after updating all my packages but it seems not to change much...

Any suggestions on how to fix this?

building ‘bioplotr_0.0.0.9000.tar.gz’ (3.2s)
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘kohonen’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘bioplotr’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/bioplotr’
Error: Failed to install 'bioplotr' from GitHub:
  (converted from warning) installation of package ‘/var/folders/vp/6qc9qd9d3y707b9ncr4rfl_sfrtxj6/T//Rtmpw9ap2N/filea2bc6c03fe8e/bioplotr_0.0.0.9000.tar.gz’ **had non-zero exit status**

**Comment by dswatson** [comment]
Just need to install kohonen separately. (This is a suggestion but not a dependency, I believe?) Apologies for the mix up! Run:

`install.packages(kohonen)`

and try again. I'll revise the Description file.
