### ISSUE TITLE
plot_drivers example from documentation does not work

### ISSUE THREAD

**Issue by mperalc** [dswatson/bioplotr#4]
Hello,

When I try to run the example from plot_drivers it gives me the error "Error: Must extract column with a single valid subscript.
x Subscript `block` has size 0 but must be size 1". Trying to adjust the blocking variable to circumvent this gives all sorts of other errors, so it seems something broke along the way. I'd be interested to use this function since some people recommended it so I hope you find the time to look into it.

Thank you!

**Comment by dswatson** [comment]
Thanks for flagging this! The `plot_drivers` function is under construction as we speak. I should have an update soon. Apologies!

**Comment by dswatson** [comment]
This should work now. The function and package are still very much under development, so please don't hesitate to raise new issues if any more come up. Thanks again!
