### ISSUE TITLE
Error: Must extract column with a single valid subscript. x Subscript `block` has size 0 but must be size 1.

### ISSUE THREAD

**Issue by saramasarone** [dswatson/bioplotr#6]
Hi David,

I'm using `drivers_plot` to see how the expression of some proteins is affected by my covariates but I keep getting this error. 
This is the code I am using:

```R
library(data.table)
library(tidyverse)
library(bioplotr)

clin <-fread('/Users/smasarone/Desktop/Atom/ML/clin_ready.csv')%>% as.data.frame()
prot_top8 <-fread('/Users/smasarone/Desktop/df_top8_proteins.csv')%>% as.data.frame()
row.names(prot_top8)<-prot_top8$TubeUniqueID
prot_top8$TubeUniqueID <-NULL
row.names(clin)<-clin$record_id
clin$record_id<-NULL
prot8_t <-t(prot_top8)
df_t<-data.frame(prot8_t)

#drivers plot
plot_drivers(df_t, clin[8:19])
``` 
and I am getting this error

```
Error: Must extract column with a single valid subscript.
x Subscript `block` has size 0 but must be size 1.
```
```
Backtrace:
 1. bioplotr::plot_drivers(df_t, clin[8:19])
 3. tibble:::`[[.tbl_df`(clin, block)
 4. tibble:::tbl_subset2(x, j = i, j_arg = substitute(i))
 5. tibble:::vectbl_as_col_location2(j, length(x), names(x), j_arg = j_arg)
 8. vctrs::vec_as_location2(j, n, names)
 9. vctrs:::result_get(...)
 ```
What am I doing wrong? I don't quite understand what the error means. (The data seems to be in the correct format.) 

Thanks,
Sara

**Comment by dswatson** [comment]
Hmm this is going to be hard to debug without the original data files (feel free to email them to me if you like?) It sounds like the function is expecting a blocking variable for some reason, although I take it you're not trying to block on anything. Are you using the latest version of `bioplotr`? I pushed some changes to `plot_drivers` just yesterday, perhaps I inadvertently introduced a bug. Please make sure you're up to date and send me the data if the problem persists.

**Comment by saramasarone** [comment]
The clinical data is a made of continuous variables only (not sure if the changes anything) and I didn't want to block on anything. I think the package is up to date, it doesn't allow me to update more than the current version (I'm on R 3.6.3).

**Comment by dswatson** [comment]
Ah so I think there may be several issues here, some of which I'm still debugging but let me just start by saying I'm not sure PCA even really makes sense in this case given that you've got 8 probes and 415 samples. This function assumes that probes exceed samples by a substantial margin, as is often the case in, say, transcriptomics. Have you tried running this with your complete proteomic matrix instead of just your top 8 probes? Alternatively, you could just plot the samples along axes for the top two probes by variance, and you would likely get something very similar to what PCA would generate. 

That said, I got an unexpected (and different) error when I ran this on my machine, so allow me to tinker a bit and get back to you.

**Comment by saramasarone** [comment]
Yeah, I tried with the entire matrix and the error is the same...
Thanks for looking into it!

**Comment by dswatson** [comment]
So I found a few bugs in my code (typical!) but I also think you've got an issue here with how you subset the `clin` data frame. You probably mean to subset by column but instead you're subsetting by row, creating a dimensionality mismatch. Try `plot_drivers(df_t, clin[, 8:19])`. This runs for me with the latest version of `bioplotr`. See attached PDF. (You may need to upgrade your version of `R`...)

[prot_example.pdf](https://github.com/dswatson/bioplotr/files/6098357/prot_example.pdf)

**Comment by dswatson** [comment]
I should also note that this plot treats `admission_time` as a character vector, although I imagine you'll want to recode it as numeric.

**Comment by saramasarone** [comment]
Thanks, yes my mistake! That's what I would do in python for columns... 😂
Thank you!

**Comment by saramasarone** [comment]
I think there's something wrong with my installation or R, I keep getting the same error even if I fix the col selection, as you suggested.

**Comment by dswatson** [comment]
Hmm that's odd. Have you uninstalled and reinstalled `bioplotr`? Also, can you confirm which version of `R` you're currently running?

**Comment by saramasarone** [comment]
It's R 3.6.3. Yes, I'll try that

**Comment by dswatson** [comment]
I think you'll need 4.0 or greater.
