### ISSUE TITLE
Plot_drivers for DNA methylation 

### ISSUE THREAD

**Issue by wellingtonboots** [dswatson/bioplotr#8]
Hi I've new to bioinformatics and I am currently analysing DNA methylation array data from Illumina EPIC array. 
I have normalized the data but due to the nature of the data, it is stored as a Genomic Ratio Set Object, and the raw data is stored as RGChannel Set Object. 
I was wondering if anyone knew how to convert these objects into a matrix that I could use plot_drivers on because it would be really useful to see what is driving the variations in the data

**Comment by dswatson** [comment]
You likely want the M-value matrix (logit-transformed beta-values), which can be extracted using the `getM` function. Check the `minfi` package documentation. I would also recommend using dedicated forums like Bioconductor and Biostars for general questions like this.
